### ISSUE TITLE
Inputs from Joysticks

### ISSUE THREAD

**Issue by taptapking** [therathatter/piu-kb-hook#1]
Does this hook work with inputs from USB Joysticks, thanks.

**Comment by therathatter** [comment]
It is possible with just the hook by modifying it, but out of the box, no.
You can however use another tool in combination with the hook to convert the joystick to keyboard for the hook to interpret. Something like AntiMicroX should work.

**Comment by taptapking** [comment]
how can I turn it into a second hook.so file? afaik AntiMicroX is a GUI program

**Comment by therathatter** [comment]
If you're not running in an environment that has a desktop environment, you will probably need to use AntiMicroX from a command line, or another tool entirely. It would not be another preloaded hook file, you would need to configure it to start on startup with the rest of the system. If you're using a minimal Linux image that is specifically for Pump, you can probably add it to the .xinitrc script before the game launches. It appears that AntiMicroX does have offer some form of command line control, but I am unsure how extensive it is. https://github.com/AntiMicroX/antimicrox?tab=readme-ov-file#command-line
